/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trafficpolicefinemis;

import java.awt.ComponentOrientation;
import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JEditorPane;

/**
 *
 * @author DE LL
 */
public class print_fine_slip extends javax.swing.JFrame {

    /**
     * Creates new form print_fine_slip
     */
    public print_fine_slip() {
        initComponents();

        jTextArea_fineSlip.setEditable(false);
        jTextArea_fineSlip.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_slipPrinter = new javax.swing.JPanel();
        jLabel_traffic_sign = new javax.swing.JLabel();
        jLabel_title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_fineSlip = new javax.swing.JTextArea();
        jButton_print_slip = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_slipPrinter.setBackground(new java.awt.Color(204, 204, 204));
        jPanel_slipPrinter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_traffic_sign.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/trafline.2.png"))); // NOI18N
        jPanel_slipPrinter.add(jLabel_traffic_sign, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 560, -1, -1));

        jLabel_title.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel_title.setForeground(new java.awt.Color(255, 51, 51));
        jLabel_title.setText("سیستم جرایم ریاست پولیس ترافیک کابل");
        jLabel_title.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_slipPrinter.add(jLabel_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 720, 40));

        jTextArea_fineSlip.setColumns(20);
        jTextArea_fineSlip.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jTextArea_fineSlip.setLineWrap(true);
        jTextArea_fineSlip.setRows(5);
        jTextArea_fineSlip.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jTextArea_fineSlip.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextArea_fineSlip.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jScrollPane1.setViewportView(jTextArea_fineSlip);

        jPanel_slipPrinter.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 640, 470));

        jButton_print_slip.setBackground(new java.awt.Color(255, 0, 0));
        jButton_print_slip.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_print_slip.setForeground(new java.awt.Color(255, 255, 255));
        jButton_print_slip.setText("چاپ");
        jButton_print_slip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_print_slipActionPerformed(evt);
            }
        });
        jPanel_slipPrinter.add(jButton_print_slip, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 560, 120, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_slipPrinter, javax.swing.GroupLayout.DEFAULT_SIZE, 943, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_slipPrinter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_print_slipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_print_slipActionPerformed
        if (jTextArea_fineSlip.getText().equals("")) {
            return;
        }

        try {
            jTextArea_fineSlip.print();
        } catch (PrinterException ex) {
            Logger.getLogger(print_fine_slip.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton_print_slipActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(print_fine_slip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(print_fine_slip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(print_fine_slip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(print_fine_slip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new print_fine_slip().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_print_slip;
    private javax.swing.JLabel jLabel_title;
    private javax.swing.JLabel jLabel_traffic_sign;
    private javax.swing.JPanel jPanel_slipPrinter;
    private javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JTextArea jTextArea_fineSlip;
    // End of variables declaration//GEN-END:variables
}
